# Generated by Django 4.2.10 on 2025-12-16 14:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tracking_information.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.CharField(max_length=15, unique=True)),
                ('date_of_purchase', models.DateField(auto_now_add=True)),
                ('time_of_purchase', models.CharField(default=tracking_information.models.get_current_time_str)),
                ('customer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_date', models.DateField(default=datetime.date.today)),
                ('shipping_address', models.CharField(max_length=255)),
                ('is_assigned', models.BooleanField(default=False)),
                ('destination_lat', models.CharField(max_length=255)),
                ('destination_lng', models.CharField(max_length=255)),
                ('business_owner_lat', models.CharField(blank=True, max_length=30, null=True)),
                ('business_owner_lng', models.CharField(blank=True, max_length=30, null=True)),
                ('rider_email', models.EmailField(blank=True, default=None, max_length=255, null=True)),
                ('rider_uuid', models.CharField(blank=True, max_length=500, null=True)),
                ('rider_lat', models.CharField(blank=True, max_length=30, null=True)),
                ('rider_lng', models.CharField(blank=True, max_length=30, null=True)),
                ('rider_name', models.CharField(blank=True, max_length=200, null=True)),
                ('rider_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(default='Nigeria', max_length=255)),
                ('product_name', models.CharField(default='unknown product', max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(blank=True, default='pending', max_length=15, null=True)),
                ('vendor', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.logistics_partner')),
            ],
        ),
    ]
