# Generated by Django 4.2.10 on 2025-11-25 22:55

from django.db import migrations, models
import tracking_information.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking_info',
            name='time_of_purchase',
            field=models.CharField(default=tracking_information.models.get_current_time_str),
        ),
    ]
