# Generated by Django 4.2.10 on 2026-02-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking_info',
            name='track_now',
            field=models.BooleanField(default=False),
        ),
    ]
