# Generated by Django 4.2.10 on 2026-03-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0002_tracking_info_track_now'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tracking_info',
            index=models.Index(fields=['owner'], name='tracking_in_owner_i_1b2d24_idx'),
        ),
        migrations.AddIndex(
            model_name='tracking_info',
            index=models.Index(fields=['date_of_purchase'], name='tracking_in_date_of_f83560_idx'),
        ),
        migrations.AddIndex(
            model_name='tracking_info',
            index=models.Index(fields=['customer_email'], name='tracking_in_custome_bb25d4_idx'),
        ),
        migrations.AddIndex(
            model_name='tracking_info',
            index=models.Index(fields=['status'], name='tracking_in_status_b0d825_idx'),
        ),
        migrations.AddIndex(
            model_name='tracking_info',
            index=models.Index(fields=['owner', 'date_of_purchase'], name='tracking_in_owner_i_e087e8_idx'),
        ),
    ]
