# Generated by Django 4.2.10 on 2026-03-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0003_tracking_info_tracking_in_owner_i_1b2d24_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=15)),
                ('lng', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
            ],
            options={
                'indexes': [models.Index(fields=['address'], name='tracking_in_address_e720de_idx'), models.Index(fields=['address', 'country'], name='tracking_in_address_cf2425_idx')],
            },
        ),
    ]
