# Generated by Django 4.2.10 on 2026-03-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0004_geolocationdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geolocationdata',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='geolocationdata',
            old_name='lng',
            new_name='longitude',
        ),
    ]
