# Generated by Django 4.2.10 on 2026-03-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0005_rename_lat_geolocationdata_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='geolocationdata',
            name='tracking_in_address_e720de_idx',
        ),
        migrations.RemoveIndex(
            model_name='geolocationdata',
            name='tracking_in_address_cf2425_idx',
        ),
        migrations.RenameField(
            model_name='geolocationdata',
            old_name='address',
            new_name='geo_address',
        ),
        migrations.AddField(
            model_name='geolocationdata',
            name='raw_address',
            field=models.CharField(default='', max_length=400, unique=True),
        ),
        migrations.AddIndex(
            model_name='geolocationdata',
            index=models.Index(fields=['raw_address'], name='tracking_in_raw_add_a42296_idx'),
        ),
        migrations.AddIndex(
            model_name='geolocationdata',
            index=models.Index(fields=['raw_address', 'country'], name='tracking_in_raw_add_69c951_idx'),
        ),
    ]
