# Generated by Django 4.2.10 on 2026-03-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0006_remove_geolocationdata_tracking_in_address_e720de_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geolocationdata',
            old_name='geo_address',
            new_name='address',
        ),
    ]
