# Generated by Django 4.2.10 on 2026-04-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0007_rename_geo_address_geolocationdata_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking_info',
            name='parcel_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
