# Generated by Django 4.2.10 on 2026-08-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0008_alter_tracking_info_parcel_number'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tracking_info',
            name='tracking_in_owner_i_1b2d24_idx',
        ),
        migrations.RemoveIndex(
            model_name='tracking_info',
            name='tracking_in_date_of_f83560_idx',
        ),
        migrations.RemoveIndex(
            model_name='tracking_info',
            name='tracking_in_custome_bb25d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='tracking_info',
            name='tracking_in_status_b0d825_idx',
        ),
        migrations.RemoveIndex(
            model_name='tracking_info',
            name='tracking_in_owner_i_e087e8_idx',
        ),
        migrations.AddIndex(
            model_name='tracking_info',
            index=models.Index(fields=['owner', 'status', '-id'], name='tracking_owner_status_id_idx'),
        ),
        migrations.AddIndex(
            model_name='tracking_info',
            index=models.Index(fields=['owner', '-id'], name='tracking_owner_id_idx'),
        ),
    ]
