# Generated by Django 4.2.10 on 2024-03-10 21:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tracking_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parcel_number", models.CharField(max_length=15, unique=True)),
                ("date_of_purchase", models.DateField(default=datetime.date.today)),
                ("delivery_date", models.DateField(default=datetime.date.today)),
                ("shipping_address", models.CharField(max_length=255)),
                ("vendor", models.CharField(max_length=255)),
                ("status", models.CharField(default="Pending", max_length=15)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
