# Generated by Django 4.2.10 on 2026-10-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0009_remove_tracking_info_tracking_in_owner_i_1b2d24_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking_info',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
