# Generated by Django 4.2.10 on 2024-04-13 18:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("logistics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tracking_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parcel_number", models.CharField(max_length=15, unique=True)),
                ("date_of_purchase", models.DateField(auto_now_add=True, null=True)),
                ("delivery_date", models.DateField(default=datetime.date.today)),
                ("shipping_address", models.CharField(max_length=255)),
                (
                    "latitude",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "longitude",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("destination_lat", models.CharField(max_length=255)),
                ("destination_lng", models.CharField(max_length=255)),
                (
                    "rider_email",
                    models.EmailField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "realtime_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("country", models.CharField(default="Nigeria", max_length=255)),
                (
                    "product_name",
                    models.CharField(default="Unknown Product", max_length=255),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("vendor", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        blank=True, default="Pending", max_length=15, null=True
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rider",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logistics.logistics_partner",
                    ),
                ),
            ],
        ),
    ]
