# Generated by Django 4.2.10 on 2024-04-13 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0001_initial"),
        ("tracking_information", "0011_alter_tracking_info_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracking_info",
            name="rider",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="logistics.logistics_partner",
            ),
        ),
    ]
