# Generated by Django 4.2.10 on 2024-05-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking_information", "0012_alter_tracking_info_rider"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracking_info",
            name="customer_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
