# Generated by Django 4.2.10 on 2024-06-09 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("tracking_information", "0013_tracking_info_customer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracking_info",
            name="time_of_purchase",
            field=models.TimeField(
                auto_now_add="53:07hrs", default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tracking_info",
            name="date_of_purchase",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
