# Generated by Django 4.2.10 on 2024-06-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking_information", "0014_tracking_info_time_of_purchase_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracking_info",
            name="time_of_purchase",
            field=models.TimeField(default="24:08hrs"),
        ),
    ]
