# Generated by Django 4.2.10 on 2024-06-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking_information", "0019_alter_tracking_info_time_of_purchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracking_info",
            name="product_name",
            field=models.CharField(default="unknown product", max_length=255),
        ),
        migrations.AlterField(
            model_name="tracking_info",
            name="status",
            field=models.CharField(
                blank=True, default="pending", max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tracking_info",
            name="time_of_purchase",
            field=models.CharField(default="11:00hrs"),
        ),
    ]
