# Generated by Django 4.2.10 on 2024-09-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0020_alter_tracking_info_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking_info',
            name='time_of_purchase',
            field=models.CharField(default='11:47hrs'),
        ),
    ]
