# Generated by Django 4.2.10 on 2024-11-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0036_alter_tracking_info_time_of_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking_info',
            name='time_of_purchase',
            field=models.CharField(default='19:02hrs'),
        ),
    ]
