# Generated by Django 4.2.10 on 2025-05-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0040_alter_tracking_info_time_of_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking_info',
            name='rider_uuid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tracking_info',
            name='time_of_purchase',
            field=models.CharField(default='12:35hrs'),
        ),
    ]
