# Generated by Django 4.2.10 on 2025-05-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0041_tracking_info_rider_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking_info',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tracking_info',
            name='time_of_purchase',
            field=models.CharField(default='21:10hrs'),
        ),
    ]
