# Generated by Django 4.2.10 on 2025-06-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0042_tracking_info_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking_info',
            name='business_owner_lat',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tracking_info',
            name='business_owner_lng',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tracking_info',
            name='time_of_purchase',
            field=models.CharField(default='17:04hrs'),
        ),
    ]
