# Generated by Django 4.2.10 on 2025-06-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0043_tracking_info_business_owner_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking_info',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tracking_info',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='tracking_info',
            name='time_of_purchase',
            field=models.CharField(default='18:33hrs'),
        ),
    ]
