# Generated by Django 4.2.10 on 2025-06-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0044_remove_tracking_info_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking_info',
            name='time_of_purchase',
            field=models.CharField(default='18:46hrs'),
        ),
    ]
