# Generated by Django 4.2.10 on 2025-06-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0048_alter_tracking_info_time_of_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking_info',
            name='rider_lat',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tracking_info',
            name='rider_lng',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tracking_info',
            name='time_of_purchase',
            field=models.CharField(default='21:37hrs'),
        ),
    ]
