# Generated by Django 4.2.10 on 2025-06-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0049_tracking_info_rider_lat_tracking_info_rider_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking_info',
            name='time_of_purchase',
            field=models.CharField(default='20:00hrs'),
        ),
    ]
