# Generated by Django 4.2.10 on 2025-09-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0060_alter_tracking_info_time_of_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking_info',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tracking_info',
            name='time_of_purchase',
            field=models.CharField(default='21:02hrs'),
        ),
    ]
