# Generated by Django 4.2.10 on 2025-09-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0061_tracking_info_is_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking_info',
            name='time_of_purchase',
            field=models.CharField(default='21:40hrs'),
        ),
    ]
