# Generated by Django 4.2.10 on 2025-10-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0071_alter_tracking_info_time_of_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking_info',
            name='realtime_location',
        ),
        migrations.AddField(
            model_name='tracking_info',
            name='rider_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tracking_info',
            name='rider_phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='tracking_info',
            name='time_of_purchase',
            field=models.CharField(default='19:21hrs'),
        ),
    ]
