# Generated by Django 4.2.10 on 2025-10-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0072_remove_tracking_info_realtime_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking_info',
            name='rider_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tracking_info',
            name='time_of_purchase',
            field=models.CharField(default='13:33hrs'),
        ),
    ]
