# Generated by Django 4.2.10 on 2025-10-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_information', '0073_alter_tracking_info_rider_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking_info',
            name='time_of_purchase',
            field=models.CharField(default='20:48hrs'),
        ),
    ]
