# Generated by Django 4.2.10 on 2024-04-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking_information", "00091_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracking_info",
            name="country",
            field=models.CharField(default="Nigeria", max_length=255),
        ),
        migrations.AddField(
            model_name="tracking_info",
            name="product_name",
            field=models.CharField(default="Unknown Product", max_length=255),
        ),
        migrations.AddField(
            model_name="tracking_info",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="tracking_info",
            name="date_of_purchase",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="tracking_info",
            name="delivery_date",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="tracking_info",
            name="status",
            field=models.CharField(
                blank=True, default="Pending", max_length=15, null=True
            ),
        ),
    ]
