# Generated by Django 4.2.10 on 2024-04-06 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tracking_information",
            "0092_tracking_info_country_tracking_info_product_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracking_info",
            name="delivery_date",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
