# Generated by Django 4.2.10 on 2024-04-06 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking_information", "0093_alter_tracking_info_delivery_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracking_info",
            name="realtime_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tracking_info",
            name="delivery_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
