# Generated by Django 4.2.10 on 2024-04-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking_information", "0094_tracking_info_realtime_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracking_info",
            name="carrier_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="tracking_info",
            name="latitude",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tracking_info",
            name="longitude",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
