# Generated by Django 4.2.10 on 2024-04-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tracking_information",
            "0095_tracking_info_carrier_id_tracking_info_latitude_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracking_info",
            name="latitude",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tracking_info",
            name="longitude",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
