# Generated by Django 4.2.10 on 2024-04-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking_information", "0096_alter_tracking_info_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracking_info",
            name="carrier_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
