# Generated by Django 4.2.10 on 2024-04-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking_information", "0097_alter_tracking_info_carrier_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracking_info",
            name="carrier_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
