# Generated by Django 4.2.10 on 2024-04-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking_information", "0098_alter_tracking_info_carrier_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tracking_info",
            name="carrier_id",
        ),
        migrations.AddField(
            model_name="tracking_info",
            name="carrier_email",
            field=models.EmailField(
                blank=True, default=None, max_length=254, null=True
            ),
        ),
    ]
