# Generated by Django 4.2.10 on 2024-04-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking_information", "0099_remove_tracking_info_carrier_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracking_info",
            name="destination_lat",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tracking_info",
            name="destination_lon",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
