# Generated by Django 4.2.10 on 2024-04-13 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "tracking_information",
            "0103_alter_tracking_info_owner_alter_tracking_info_rider",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tracking_info",
            name="rider",
        ),
        migrations.RemoveField(
            model_name="tracking_info",
            name="rider_email",
        ),
    ]
