#!/usr/bin/python3
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from tracking_information.models import Tracking_info
from tracking_information.serializer import Tracking_infoSerializer
from business.views.business_owner_permission import IsBusinessOwner

""" Route that handles retrieving the tracking information generated by a business owner"""

class RetrieveAllView(APIView):
    permission_classes = [IsBusinessOwner,]

    def __init__(self):
        
        self.all_tracking = Tracking_info.objects.all()
    
    # method that handles returning all tracking number generated by a user
    def get(self, request, *args, **kwargs):
        try:
            all_tracking = self.all_tracking.filter(owner=request.user.id)
            serializer = Tracking_infoSerializer(all_tracking, many=True)
            return Response(serializer.data, status=status.HTTP_200_OK)
        except Exception:
            raise ValueError(
                    "An Error occured while fetching all the \
                    Tracking number generated by %s"% request.user.name \
                    )
