# Generated by Django 4.2.7 on 2024-02-08 20:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "track",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(), default=list, size=None
                    ),
                ),
            ],
        ),
    ]
