# Generated by Django 4.2.10 on 2026-04-07 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_payment_reference_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='autorization_url',
            new_name='authorization_url',
        ),
    ]
