# Generated by Django 4.2.10 on 2026-04-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_payment_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='idempotency_key',
            field=models.UUIDField(unique=True),
        ),
    ]
