# Generated by Django 4.2.10 on 2026-04-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_alter_payment_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sender_account_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_bank',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_country',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_narration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
