# Generated by Django 4.2.10 on 2026-04-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_payment_sender_account_number_payment_sender_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='exp_month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='exp_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
