# Generated by Django 4.2.10 on 2026-04-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_payment_card_type_payment_exp_month_payment_exp_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='country_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
