# Generated by Django 4.2.10 on 2026-04-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_payment_account_name_payment_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vat',
            field=models.FloatField(default=0.0),
        ),
    ]
