# Generated by Django 4.2.10 on 2024-03-09 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parcel_number", models.CharField(max_length=15)),
                ("date_of_purchase", models.DateField(default=datetime.date.today)),
                ("delivery_date", models.DateField(default=datetime.date.today)),
                ("shipping_address", models.CharField(max_length=255)),
                ("vendor", models.CharField(max_length=255)),
                ("status", models.CharField(default="Pending", max_length=15)),
            ],
            options={
                "verbose_name": "tracking",
            },
        ),
    ]
