# Generated by Django 4.2.7 on 2024-02-04 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trackings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parcel_num", models.CharField(max_length=50)),
                (
                    "date_of_purchase",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("shipping_address", models.CharField(max_length=300)),
                ("estimated_delivery_date", models.DateTimeField()),
                ("vendor", models.CharField(max_length=500)),
                ("status", models.CharField(default="Pending")),
            ],
        ),
        migrations.DeleteModel(
            name="Tracking",
        ),
    ]
