# Generated by Django 4.2.7 on 2024-02-04 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0002_trackings_delete_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackings",
            name="estimated_delivery_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
