# Generated by Django 4.2.10 on 2025-12-16 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsOwnerStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logistics_partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(blank=True, max_length=55, null=True)),
                ('lng', models.CharField(blank=True, max_length=55, null=True)),
                ('identity_card_type', models.CharField(blank=True, max_length=120, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('plate_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('owner', models.IntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=50, null=True)),
                ('logistics_owner_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('profile_pic_key', models.CharField(blank=True, max_length=300, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_image_key', models.CharField(blank=True, max_length=300, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True)),
                ('terms_and_condition', models.BooleanField(blank=True, null=True)),
                ('is_busy', models.BooleanField(blank=True, null=True)),
                ('total_delivery', models.IntegerField(default=0)),
                ('total_assigned_orders', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('status', models.CharField(default='inactive', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
