# Generated by Django 4.2.10 on 2024-04-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logistics_partner",
            name="lat",
            field=models.CharField(default=None, max_length=55),
        ),
        migrations.AddField(
            model_name="logistics_partner",
            name="lng",
            field=models.CharField(default=None, max_length=55),
        ),
    ]
