# Generated by Django 4.2.10 on 2025-12-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics_partner',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
