# Generated by Django 4.2.10 on 2026-02-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_logistics_partner_is_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics_partner',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
