# Generated by Django 4.2.10 on 2024-04-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0002_logistics_partner_lat_logistics_partner_lng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logistics_partner",
            name="lat",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name="logistics_partner",
            name="lng",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
