# Generated by Django 4.2.10 on 2025-09-24 23:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_logistics_partner_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics_partner',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='logistics_partner',
            name='identity_card_type',
            field=models.CharField(default='unknown', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logistics_partner',
            name='logistics_owner_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='logistics_partner',
            name='nationality',
            field=models.CharField(default='nigeria', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logistics_partner',
            name='owner',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logistics_partner',
            name='plate_number',
            field=models.CharField(default='sdfghj', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logistics_partner',
            name='profile_pic_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logistics_partner',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logistics_partner',
            name='terms_and_condition',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logistics_partner',
            name='vehicle_color',
            field=models.CharField(default='red', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logistics_partner',
            name='vehicle_model',
            field=models.CharField(default='corolla', max_length=50),
            preserve_default=False,
        ),
    ]
