# Generated by Django 4.2.10 on 2026-02-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_logistics_partner_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logistics_partner',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='logistics_partner',
            name='rider_updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
