# Generated by Django 4.2.10 on 2025-09-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_logistics_partner_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics_partner',
            name='id_number',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
