# Generated by Django 4.2.10 on 2026-02-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_remove_logistics_partner_updated_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logistics_partner',
            old_name='rider_updated_on',
            new_name='updated_on',
        ),
    ]
