# Generated by Django 4.2.10 on 2025-09-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_alter_logistics_partner_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics_partner',
            name='profile_pic_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
