# Generated by Django 4.2.10 on 2026-03-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_rename_rider_updated_on_logistics_partner_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics_partner',
            name='total_declined_orders',
            field=models.IntegerField(default=0),
        ),
    ]
