# Generated by Django 4.2.10 on 2025-09-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_alter_logistics_partner_profile_pic_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics_partner',
            name='plate_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
