# Generated by Django 4.2.10 on 2026-03-16 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_logistics_partner_total_declined_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logistics_partner',
            name='total_declined_orders',
        ),
    ]
