# Generated by Django 4.2.10 on 2026-03-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_remove_logistics_partner_total_declined_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics_partner',
            name='total_declined_orders',
            field=models.IntegerField(default=0),
        ),
    ]
