# Generated by Django 4.2.10 on 2025-09-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_logistics_partner_plate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics_partner',
            name='vehicle_image_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
