# Generated by Django 4.2.10 on 2026-04-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_logistics_partner_total_declined_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics_partner',
            name='expo_notif_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
