# Generated by Django 4.2.10 on 2025-09-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_logistics_partner_vehicle_image_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics_partner',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='logistics_partner',
            name='status',
            field=models.CharField(default='inactive', max_length=50),
        ),
        migrations.AddField(
            model_name='logistics_partner',
            name='total_delivery',
            field=models.IntegerField(default=0),
        ),
    ]
