# Generated by Django 4.2.10 on 2026-07-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_logistics_partner_expo_notif_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics_partner',
            name='id_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='logistics_partner',
            name='identity_card_type',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
    ]
