# Generated by Django 4.2.10 on 2025-10-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_logistics_partner_rating_logistics_partner_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics_partner',
            name='total_assigned_orders',
            field=models.IntegerField(default=0),
        ),
    ]
