# Generated by Django 4.2.10 on 2026-07-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_alter_logistics_partner_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics_partner',
            name='id_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
