# Generated by Django 4.2.10 on 2025-10-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_logistics_partner_total_assigned_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics_partner',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='logistics_partner',
            name='identity_card_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='logistics_partner',
            name='plate_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='logistics_partner',
            name='terms_and_condition',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logistics_partner',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logistics_partner',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
