# Generated by Django 4.2.10 on 2025-10-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_alter_logistics_partner_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics_partner',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
