# Generated by Django 4.2.10 on 2026-07-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_alter_logistics_partner_id_number'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='logistics_partner',
            index=models.Index(fields=['id_number', 'identity_card_type'], name='logistics_l_id_numb_ae4f80_idx'),
        ),
    ]
