# Generated by Django 4.2.10 on 2026-07-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_logistics_partner_logistics_l_id_numb_ae4f80_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='logistics_partner',
            new_name='rider_id_card_idx',
            old_name='logistics_l_id_numb_ae4f80_idx',
        ),
        migrations.AlterField(
            model_name='logistics_partner',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logistics_partner',
            name='identity_card_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
