# Generated by Django 4.2.7 on 2024-01-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="name",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
