# Generated by Django 4.2.7 on 2024-01-04 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_author_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="relationship",
        ),
        migrations.AddField(
            model_name="books",
            name="relationship",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="books.author",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
