#!/usr/bin/python3
from business.models import Business_owner
from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase
from rest_framework.utils.serializer_helpers import ReturnList
from rest_framework_simplejwt.tokens import AccessToken
from user.models import User

class TestRetrieveAllTracking(APITestCase):
    """ 
    Retrieve all tracking generated by a business owner
    """

    def setUp(self):
        self.user = User.objects.create(
                name='Jane Doe',
                email='Jane.Doe@tester.com',
                phone_number='09015885211',
                address='Lagos',
                password='password',
                account_type='business'
                )
        self.business = Business_owner.objects.create(user=self.user, business_name='Hue Logistics')
        self.data = {'product': 'Medicine','shipping_address':'Lagos, Ibadan', 'country': 'Nigeria', 'quantity': 2, 'delivery_date': '2024-12-12'}
        self.token = AccessToken.for_user(self.user)
        self.client.credentials(HTTP_AUTHORIZATION="Bearer %s"% self.token)

    def test_retrieve_all(self):
        # retrieve all tracking generated by business owner
        url1 = reverse('generate-tracking')
        res1 = self.client.post(url1, data=self.data, format='json')
  
        url = reverse('trackings')
        res = self.client.get(url, format='json')
        self.assertTrue(res1.status_code == 201)
        self.assertTrue(res.status_code == 200)
        self.assertTrue(type(res.data) == ReturnList)
        self.assertEqual(res.data[0].get('shipping_address'), 'Lagos, Ibadan')
