# Generated by Django 4.2.10 on 2025-06-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_business_owner_latitude_business_owner_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_owner',
            name='business_owner_uuid',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='business owner uuid'),
        ),
    ]
