# Generated by Django 4.2.10 on 2025-06-05 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_owner_business_owner_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_owner',
            name='business_owner_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
