# Generated by Django 4.2.10 on 2025-06-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_business_owner_business_owner_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_owner',
            name='profile_pic_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
