# Generated by Django 4.2.10 on 2025-10-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_business_owner_profile_pic_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_owner',
            name='terms_and_condition',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
