# Generated by Django 4.2.10 on 2025-10-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_business_owner_terms_and_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_owner',
            name='subscription_type',
            field=models.CharField(default='trial', max_length=20),
        ),
    ]
