# Generated by Django 4.2.10 on 2026-04-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_business_owner_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_owner',
            name='subscription_type',
            field=models.CharField(default='payu', max_length=20),
        ),
    ]
