# Generated by Django 4.2.10 on 2024-02-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
