# Generated by Django 4.2.10 on 2024-02-15 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logistics_partner",
            name="user",
        ),
        migrations.DeleteModel(
            name="Business_owner",
        ),
        migrations.DeleteModel(
            name="Logistics_partner",
        ),
    ]
