# Generated by Django 4.2.10 on 2024-03-10 21:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
