# Generated by Django 4.2.10 on 2024-11-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_otp_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='otp',
        ),
        migrations.AddField(
            model_name='otp',
            name='hashed_otp',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='otp'),
        ),
        migrations.AddField(
            model_name='otp',
            name='otp_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
