# Generated by Django 4.2.10 on 2024-11-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_otp_otp_otp_hashed_otp_otp_otp_expiration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='logo',
            new_name='avatar',
        ),
    ]
