# Generated by Django 4.2.10 on 2024-11-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_logo_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
