# Generated by Django 4.2.10 on 2025-06-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='avatar'),
        ),
    ]
