# Generated by Django 4.2.10 on 2025-09-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Country'),
        ),
    ]
