# Generated by Django 4.2.10 on 2025-09-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wants_marketing_emails',
            field=models.BooleanField(default=True),
        ),
    ]
