# Generated by Django 4.2.10 on 2025-10-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_wants_marketing_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
