# Generated by Django 4.2.10 on 2025-10-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(default='trial', max_length=20),
        ),
    ]
