# Generated by Django 4.2.10 on 2025-10-17 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_subscription_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_type',
        ),
    ]
