# Generated by Django 4.2.10 on 2026-09-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_phone', models.CharField(blank=True, max_length=21, null=True)),
                ('receiver_phone', models.CharField(blank=True, max_length=21, null=True)),
                ('category', models.CharField(default='utility', max_length=21)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('status_id', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=40, null=True)),
                ('billable', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
