# Generated by Django 4.2.10 on 2026-09-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappnotification',
            old_name='created_at',
            new_name='sent_at',
        ),
        migrations.AddField(
            model_name='whatsappnotification',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappnotification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
