# Generated by Django 4.2.10 on 2026-09-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_created_at_whatsappnotification_sent_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappnotification',
            old_name='status_id',
            new_name='message_status_id',
        ),
        migrations.RemoveField(
            model_name='whatsappnotification',
            name='status',
        ),
        migrations.AddField(
            model_name='whatsappnotification',
            name='message_status',
            field=models.CharField(default='sent', max_length=15),
        ),
        migrations.AddField(
            model_name='whatsappnotification',
            name='parcel_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='whatsappnotification',
            name='parcel_status',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
